---
- hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_distribution == 'Ubuntu'

    - name: Clear the yum cache
      command: yum clean all
      tags:
        - skip_ansible_lint
      when: ansible_distribution == 'CentOS'

    - name: Install initscripts
      package:
        name: initscripts

    - name: CA Certificates
      package:
        name: ca-certificates

    - name: Install curl
      package:
        name: curl

    - name: Download JDK
      get_url:
        url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
        headers: "Cookie:oraclelicense=accept-securebackup-cookie"
        dest: /tmp/jdk-8u131-linux-x64.tar.gz

    - name: Extract JDK tarball
      unarchive:
        src: /tmp/jdk-8u131-linux-x64.tar.gz
        dest: /opt
        creates: /opt/jdk1.8.0_131/
        remote_src: yes

- hosts: standalone
  roles:
    - role: ansible-role-jboss
      jboss_properties:
          jboss.bind.address.management: 0.0.0.0
